"""Add neighbourhood and street fields, remove unseen_crossing table

Revision ID: 6935ec650e02
Revises: 5ebf212a4a56
Create Date: 2025-04-26 11:18:31.471233

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6935ec650e02'
down_revision: Union[str, None] = '5ebf212a4a56'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
