"""Add neighbourhood and street fields to Crossing model

Revision ID: fc470737f392
Revises: 6935ec650e02
Create Date: 2025-04-26 11:25:28.028204

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fc470737f392'
down_revision: Union[str, None] = '6935ec650e02'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('unseen_crossing')
    op.add_column('crossing', sa.Column('neighbourhood', sa.String(length=100), nullable=True))
    op.add_column('crossing', sa.Column('street', sa.String(length=100), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('crossing', 'street')
    op.drop_column('crossing', 'neighbourhood')
    op.create_table('unseen_crossing',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('user_id', sa.VARCHAR(length=36), nullable=False),
    sa.Column('crossing_id', sa.VARCHAR(length=36), nullable=False),
    sa.ForeignKeyConstraint(['crossing_id'], ['crossing.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'crossing_id')
    )
    # ### end Alembic commands ###
